# -*- coding: utf-8 -*-
"""Untitled16.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1LdZqW9w3Nurt0q9wwwGNo6ii0_z6vpBx
"""

import sys
if 'streamlit' not in sys.modules:
  !pip install streamlit

import streamlit as st
import pandas as pd
import plotly.express as px

# 1. Load the dataset
# Note: In Colab, the path is usually '/content/Sample - Superstore.csv'
df = pd.read_csv('/content/Sample - Superstore.csv', encoding='latin1')

# 2. Preprocessing
df['Order Date'] = pd.to_datetime(df['Order Date'])

# 3. Dashboard Title
st.title("🚀 Business Sales Performance Dashboard")
st.markdown("Analysis of Sales, Profit, and Category Trends")

# 4. Create KPIs (Top Row)
total_sales = df['Sales'].sum()
total_profit = df['Profit'].sum()
avg_discount = df['Discount'].mean()

col1, col2, col3 = st.columns(3)
col1.metric("Total Sales", f"${total_sales:,.2f}")
col2.metric("Total Profit", f"${total_profit:,.2f}")
col3.metric("Avg Discount", f"{avg_discount:.2%}")

# 5. Sales Trend Chart (Time Series)
st.subheader("Monthly Sales Trend")
df_trend = df.resample('M', on='Order Date')['Sales'].sum().reset_index()
fig_trend = px.line(df_trend, x='Order Date', y='Sales', title="Sales Over Time")
st.plotly_chart(fig_trend)

# 6. Profit by Category (Bar Chart)
st.subheader("Profitability by Category")
fig_bar = px.bar(df, x='Category', y='Profit', color='Region', barmode='group')
st.plotly_chart(fig_bar)

# 7. Business Recommendations (Crucial for the Internship)
st.divider()
st.header("💡 Strategic Recommendations")
st.write("""
- **Focus on High-Profit Regions:** The West region shows the strongest margins.
- **Review Technology Discounts:** While Sales are high in Tech, Profit margins are being hit by aggressive discounting.
- **Inventory Management:** Standard Class shipping is the most used; consider optimizing stock for this segment.
""")